name: mobile_voting_verifier
description: Second device verification tool for implementations based on the Polyas system. Created for "E-Voting - Trust in Verification Systems"  BSc project ITU Copenhagen.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+2

environment:
  #sdk: '>=2.19.1 <3.0.0'
  sdk: ^3.0.0-218.1.beta

dependencies:
  local_cryptography:
    path: packages/local_cryptography
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  mobile_scanner: ^2.1.0
  url_launcher: ^6.1.9
  pinput: ^2.2.31
  google_fonts: ^4.0.3
  test: ^1.22.0
  mockito: ^5.3.2
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0
  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  open_filex: ^4.3.2
  pdf: ^3.8.4
  qr_code_scanner: ^1.0.1
flutter_icons:
  android: true
  ios: true
  image_path: "assets/Group 1Logo.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
# The following section is specific to Flutter packages.
flutter:
  assets:
    - "assets/public_parameters.json"
    - "assets/mock_ballot_spec.json"
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
